### PR TITLE
Make Vanilla a peer dependency

### PR DESCRIPTION
**Pull request by huwshimi**
## Done

- Added Vanilla as peer and dev dependencies.

### Storybook

To see rendered examples of all react-components, run:

```shell
yarn start
```

### QA in your project

from `react-components` run:

```shell
yarn build
npm pack
```

Install the resulting tarball in your project with:

```shell
yarn add <path-to-tarball>
```

### QA steps

- Use `yarn link` to test this with another project.

## Fixes

Fixes: #322 .

### CODE REVIEW

**Review by bartaz — COMMENTED** [review]
LGTM, thanks!

**Comment by huwshimi** [comment]
Thanks @bartaz this just needs a green tick.

**Review by bartaz — APPROVED** [review]
Sorry, LGTM!

**Comment by huwshimi** [comment]
No worries, thanks @bartaz!

**Pull request merged**
