### PR TITLE
Preparing release 0.10.0

### PR DESCRIPTION
**Pull request by bartaz**
## Done

- Updated changelog
- Rebuilt the docs

### CODE REVIEW

**Comment by bartaz** [comment]
@huwshimi @squidsoup Would you be able to review that one and release to NPM?

**Comment by hatched** [comment]
The Search & Filter component (Beta) has been merged now as well. I'm not sure if you'll want to include that in this but I wanted to mention it.

**Comment by bartaz** [comment]
> The Search & Filter component (Beta) has been merged now as well. I'm not sure if you'll want to include that in this but I wanted to mention it.

Hmm... can't see it anywhere here in [closed PRs](https://github.com/canonical-web-and-design/react-components/pulls?q=is%3Apr+is%3Aclosed), this view confuses me...

And I guess now with new PR merged both changelog and docs need to be updated here.

**Comment by bartaz** [comment]
I don't have time tonight to look into it, but it seems search and filter is not working in storybook:

Screenshot 2020-09-15 at 20 37 37

**Comment by huwshimi** [comment]
> I don't have time tonight to look into it, but it seems search and filter is not working in storybook:
> 

I have a fix for that in my branch (I was modifying that component anyway): https://github.com/canonical-web-and-design/react-components/pull/275.

It might be easiest to restart this branch after that lands. I can do a release if it lands during my day.

**Review by huwshimi — APPROVED** [review]

**Pull request merged**
