### PR TITLE
Update jsx transform

### PR DESCRIPTION
**Pull request by huwshimi**
## Done

- Update to the new JSX transform.

## QA

N/A

## Fixes

Fixes: #312.

### CODE REVIEW

**Comment by huwshimi** [comment]
Well I just don't know what's going on here. Some config somewhere must be wrong as it's loading duplicates of React.

`Module parse failed: Identifier 'React' has already been declared`

**Comment by bartaz** [comment]
Yes, that's weird, it seems to fail on `build-docs` step, so it seems like storybook building is not working.
Fails on demo jenkins as well: https://jenkins.canonical.com/webteam/view/demos/job/start-demo/9492/console

**Comment by bartaz** [comment]
Found a couple of JSX transform related bug reports in Storybook, nothing directly about this kind of error, but maybe some config recommendations would work for us:

https://github.com/storybookjs/storybook/issues/13421
https://github.com/storybookjs/storybook/issues/12952
https://github.com/storybookjs/storybook/issues/12881

**Comment by cristinadresch** [comment]
@huwshimi will you have time to look at it this iteration?

**Comment by huwshimi** [comment]
It looks like there might be issues with the new JSX transform and Storybook so I'll close this for now and we can try again in the future once Storybook supports it.

**Pull request closed without merging**
